/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ViewFrame;

import com.ViewFrame.MenuEmployee.homeFrame;
import com.ViewFrame.MenuEmployee.patientFrame;
import com.ViewFrame.MenuEmployee.patientAreaFrame;
import com.ViewFrame.MenuEmployee.patientHomeFrame;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author pv
 */
public class EmployeeDetailFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDetailFrame
     */

    public EmployeeDetailFrame() {
        
        super("Employee Detail");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        this.setSize(width, height);
        initComponents();

        homeFrame home = new homeFrame();
        jDesktopPane1.add(home).setVisible(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbDetail = new javax.swing.JLabel();
        lbPaiter = new javax.swing.JLabel();
        lbPaiterHome = new javax.swing.JLabel();
        lbPaiterArea = new javax.swing.JLabel();
        lbBack = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelDetailEmp = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLayeredPane1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ViewFrame/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));

        lbDetail.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbDetail.setForeground(new java.awt.Color(255, 255, 255));
        lbDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDetail.setText("Trang chủ");
        lbDetail.setBorder(null);
        lbDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDetailMouseClicked(evt);
            }
        });

        lbPaiter.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbPaiter.setForeground(new java.awt.Color(255, 255, 255));
        lbPaiter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPaiter.setText("Bệnh nhân");
        lbPaiter.setBorder(null);
        lbPaiter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPaiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPaiterMouseClicked(evt);
            }
        });

        lbPaiterHome.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbPaiterHome.setForeground(new java.awt.Color(255, 255, 255));
        lbPaiterHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPaiterHome.setText("Bệnh nhân tại nhà");
        lbPaiterHome.setBorder(null);
        lbPaiterHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPaiterHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPaiterHomeMouseClicked(evt);
            }
        });

        lbPaiterArea.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbPaiterArea.setForeground(new java.awt.Color(255, 255, 255));
        lbPaiterArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPaiterArea.setText("Bệnh nhân  tại khu cách ly");
        lbPaiterArea.setBorder(null);
        lbPaiterArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPaiterArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPaiterAreaMouseClicked(evt);
            }
        });

        lbBack.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbBack.setForeground(new java.awt.Color(255, 255, 255));
        lbBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBack.setText("Đăng xuất");
        lbBack.setBorder(null);
        lbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPaiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPaiterHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPaiterArea, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
            .addComponent(lbBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPaiterHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPaiterArea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Vesion 7.7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelDetailEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelDetailEmp.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetailEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDetailEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDetailMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        System.out.println("Cliked");
        homeFrame home = new homeFrame();
        patientFrame patient = new patientFrame();
        patientHomeFrame patientHome = new patientHomeFrame();
        patientAreaFrame patientArea = new patientAreaFrame();
        jDesktopPane1.add(patient).setVisible(false);
        jDesktopPane1.add(patientHome).setVisible(false);
        jDesktopPane1.add(patientArea).setVisible(false);
        jDesktopPane1.add(home).setVisible(true);
    }//GEN-LAST:event_lbDetailMouseClicked

    private void lbPaiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPaiterMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        
        homeFrame home = new homeFrame();
        patientFrame patient = new patientFrame();
        patientHomeFrame patientHome = new patientHomeFrame();
        patientAreaFrame patientArea = new patientAreaFrame();
        jDesktopPane1.add(home).setVisible(false);
        jDesktopPane1.add(patientHome).setVisible(false);
        jDesktopPane1.add(patientArea).setVisible(false);
        jDesktopPane1.add(patient).setVisible(true);
    }//GEN-LAST:event_lbPaiterMouseClicked

    private void lbPaiterHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPaiterHomeMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        
        homeFrame home = new homeFrame();
        patientFrame patient = new patientFrame();
        patientHomeFrame patientHome = new patientHomeFrame();
        patientAreaFrame patientArea = new patientAreaFrame();
        jDesktopPane1.add(home).setVisible(false);
        jDesktopPane1.add(patient).setVisible(false);
        jDesktopPane1.add(patientArea).setVisible(false);
        jDesktopPane1.add(patientHome).setVisible(true);
    }//GEN-LAST:event_lbPaiterHomeMouseClicked

    private void lbPaiterAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPaiterAreaMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        
        homeFrame home = new homeFrame();
        patientFrame patient = new patientFrame();
        patientHomeFrame patientHome = new patientHomeFrame();
        patientAreaFrame patientArea = new patientAreaFrame();
        jDesktopPane1.add(home).setVisible(false);
        jDesktopPane1.add(patient).setVisible(false);
        jDesktopPane1.add(patientHome).setVisible(false);
        jDesktopPane1.add(patientArea).setVisible(true);
    }//GEN-LAST:event_lbPaiterAreaMouseClicked

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "Đăng xuất tài khoản");
        setVisible(false);
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_lbBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetailFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbBack;
    private javax.swing.JLabel lbDetail;
    private javax.swing.JLabel lbPaiter;
    private javax.swing.JLabel lbPaiterArea;
    private javax.swing.JLabel lbPaiterHome;
    private javax.swing.JPanel panelDetailEmp;
    // End of variables declaration//GEN-END:variables
}
